import type { RepoAnalysis } from "./types.js";

/** A generated context file: relative output path + markdown content. */
export interface GeneratedFile {
  path: string;
  content: string;
}

const HEADER = (title: string) =>
  `<!-- Generated by mindset-ctx. Re-run \`ctx generate\` to refresh; hand-edits below the marker line are preserved. -->\n\n# ${title}\n`;

/** Marker after which hand-written content is preserved across regenerations. */
export const MANUAL_MARKER = "<!-- ctx:manual — everything below this line is yours, never overwritten -->";

function langSummary(a: RepoAnalysis): string {
  if (a.languages.length === 0) return "No source files detected yet.";
  return a.languages
    .slice(0, 5)
    .map((l) => `${l.language} (${l.files} file${l.files > 1 ? "s" : ""})`)
    .join(", ");
}

function scriptsTable(a: RepoAnalysis): string {
  const entries = Object.entries(a.scripts);
  if (entries.length === 0) return "_No package scripts defined._";
  return ["| Command | What it does |", "| --- | --- |", ...entries.map(([k, v]) => `| \`npm run ${k}\` | \`${v}\` |`)].join("\n");
}

function layoutList(a: RepoAnalysis): string {
  if (a.layout.length === 0) return "_Empty repository._";
  return a.layout.map((e) => `- \`${e.path}\`${e.note ? ` — ${e.note}` : ""}`).join("\n");
}

export function generateClaudeMd(a: RepoAnalysis): GeneratedFile {
  const content = `${HEADER(`${a.name} — Claude context`)}
${a.description ? `> ${a.description}\n` : ""}
## What this project is

${a.description ?? "_Describe the project purpose here (below the manual marker) so agents inherit it._"}

**Stack:** ${langSummary(a)}${a.frameworks.length ? ` · ${a.frameworks.join(", ")}` : ""}

## Repository layout

${layoutList(a)}

## Commands

${scriptsTable(a)}

## Working conventions for agents

- ${a.hasTests ? "Run the test suite before committing (`npm test`)." : "There is no test suite yet — add tests alongside any non-trivial change."}
- ${a.hasCI ? "CI runs on every push; keep it green." : "No CI configured yet — verify changes locally."}
- Match the style of surrounding code; do not introduce new dependencies without a clear reason.
- Keep generated context fresh: after structural changes, re-run \`ctx generate\`.

${MANUAL_MARKER}
`;
  return { path: "CLAUDE.md", content };
}

export function generateAgentsMd(a: RepoAnalysis): GeneratedFile {
  const content = `${HEADER(`${a.name} — Agent guidelines`)}
Instructions for AI coding agents (Claude Code, Cursor, Copilot Workspace, …) working in this repository.

## Golden rules

1. Read \`CLAUDE.md\` first; it is the canonical project context.
2. Never push directly to \`${a.defaultBranch ?? "main"}\` — work on a feature branch and open a PR.
3. ${a.hasTests ? "All changes must pass `npm test`." : "Add or update tests when you touch behavior."}
4. Prefer small, reviewable diffs over sweeping refactors.
5. Consult the memory layer (\`.context/memory.jsonl\` or \`GET /v1/memory/search?q=…\`) before re-deciding something a past PR already settled.

## Build & verify

${scriptsTable(a)}

## Boundaries

- Do not edit generated files above their manual marker; run \`ctx generate\` instead.
- Do not commit secrets, tokens or \`.env\` files.
- Dependencies: ${a.dependencies.length > 0 ? `currently ${a.dependencies.length} (see manifest${a.manifests.length > 1 ? "s" : ""}: ${a.manifests.join(", ")})` : "none yet"} — keep the footprint minimal.

${MANUAL_MARKER}
`;
  return { path: "AGENTS.md", content };
}

export function generateArchitectureDoc(a: RepoAnalysis): GeneratedFile {
  const content = `${HEADER(`${a.name} — Architecture`)}
_Auto-generated snapshot of the repository structure. Narrative sections live below the manual marker._

## Overview

- **Name:** ${a.name}
- **Description:** ${a.description ?? "—"}
- **Primary languages:** ${langSummary(a)}
- **Frameworks / tooling:** ${a.frameworks.length ? a.frameworks.join(", ") : "—"}
- **Manifests:** ${a.manifests.length ? a.manifests.join(", ") : "—"}
- **Tests:** ${a.hasTests ? "yes" : "not detected"} · **CI:** ${a.hasCI ? "yes" : "not detected"}
- **Files scanned:** ${a.fileCount}
${a.remote ? `- **Remote:** ${a.remote}` : ""}

## Top-level layout

${layoutList(a)}

## Dependency surface

${a.dependencies.length ? a.dependencies.map((d) => `- \`${d}\``).join("\n") : "_No declared dependencies._"}

${MANUAL_MARKER}
`;
  return { path: "docs/ARCHITECTURE.md", content };
}

export function generateContributing(a: RepoAnalysis): GeneratedFile {
  const content = `${HEADER(`Contributing to ${a.name}`)}
Thanks for contributing! This guide applies to humans **and** AI agents.

## Workflow

1. Fork / branch from \`${a.defaultBranch ?? "main"}\`.
2. Make your change with tests where behavior changes.
3. ${Object.keys(a.scripts).includes("test") ? "Run `npm test` and make sure it passes." : "Verify your change locally."}
4. Open a pull request with a clear description of **what** and **why**.

## Commit style

- Imperative, present tense: “add X”, “fix Y”.
- One logical change per commit.

## For AI agents

- Follow \`AGENTS.md\` and \`CLAUDE.md\`.
- Regenerate context after structural changes: \`ctx generate\`.

${MANUAL_MARKER}
`;
  return { path: "CONTRIBUTING.md", content };
}

export function generatePromptTemplates(a: RepoAnalysis): GeneratedFile {
  const content = `${HEADER(`${a.name} — Prompt templates`)}
Reusable prompt templates for dev agents. Interpolate \`{{placeholders}}\` before use.

## Implement a feature

\`\`\`text
You are working in the ${a.name} repository (${langSummary(a)}).
Read CLAUDE.md and AGENTS.md first.
Task: {{feature_description}}
Constraints: keep the diff minimal, ${a.hasTests ? "add tests, run npm test" : "verify locally"}, follow existing code style.
Search .context/memory.jsonl for prior decisions related to: {{keywords}}.
\`\`\`

## Fix a bug

\`\`\`text
Bug report: {{bug_description}}
Reproduce it first, then fix the root cause (not the symptom).
Reference the memory layer for related past changes: {{keywords}}.
Deliverables: failing test that reproduces the bug, the fix, passing suite.
\`\`\`

## Review a pull request

\`\`\`text
Review PR {{pr_number}} in ${a.name}.
Focus on: correctness, regressions, adherence to AGENTS.md conventions.
Flag anything that contradicts decisions recorded in the memory layer.
\`\`\`

${MANUAL_MARKER}
`;
  return { path: ".context/prompts.md", content };
}

/** Generate every context file for a repo analysis. */
export function generateAll(a: RepoAnalysis): GeneratedFile[] {
  return [
    generateClaudeMd(a),
    generateAgentsMd(a),
    generateArchitectureDoc(a),
    generateContributing(a),
    generatePromptTemplates(a),
  ];
}

/**
 * Merge a freshly generated file with an existing one on disk:
 * everything the user wrote below MANUAL_MARKER is carried over.
 */
export function mergePreservingManual(fresh: string, existing: string | null): string {
  if (!existing) return fresh;
  const idx = existing.indexOf(MANUAL_MARKER);
  if (idx === -1) return fresh;
  const manual = existing.slice(idx + MANUAL_MARKER.length);
  const freshIdx = fresh.indexOf(MANUAL_MARKER);
  return fresh.slice(0, freshIdx + MANUAL_MARKER.length) + manual;
}
